var jQuerySlideshow1_json = 
	{
 "innernavbaritemthumb.active.opacity": "1",
 "innerbulletsitem.active.backgroundType": "normal",
 "subcaption.opacity": "1",
 "innernumbers_next.opacity": "1",
 "innerslider.left": "0px",
 "innerslider.top": "0px",
 "innerbullets_next.left": "230px",
 "innerbutton.next.left": "0px",
 "align": "left",
 "innernumbers_next.top": "0px",
 "innernumbers_back.top": "0px",
 "stopAtInteraction": true,
 "preloading": "includes/jQuerySlideshow/preloading.gif",
 "innerplaypause.halign": "right",
 "innernumbers.top": "0px",
 "innersubcaption.opacity": "1",
 "innernumbers_back.valign": "top",
 "innercurrentslide.slideEffectEasing": "linear",
 "hideOnMouseOut": true,
 "fadeDuration": "1000",
 "innercaption.slideEffect": "fadeIn",
 "innerbullets_back.halign": "center",
 "innersubcaption.mouseOutEffect": "fadeIn",
 "innerthumbscrollitem.orientation": "horizontal",
 "width": "944px",
 "tooltip.offsY": "20px",
 "innerbutton.back.top": "0px",
 "innerbutton.next.hideOnMouseOut": false,
 "auto": true,
 "speed": "1000",
 "innernavbaritem.orientation": "horizontal",
 "innernavbaritemthumb.hover.mouseOverEffectEasing": "linear",
 "innercaption.mouseOutEffectDelay": "0",
 "innerplaypause.top": "5px",
 "innerthumbscroll_back.opacity": "1",
 "innerbulletsitem.backgroundType": "normal",
 "innerplaypause.mouseOutEffectDuration": "1000",
 "tooltip.reverseSide": false,
 "innernavbar.valign": "bottom",
 "height": "350px",
 "innerthumbscrollitemthumb.hover.opacity": "1",
 "gifPath": "includes/jQuerySlideshow/x.gif",
 "innercurrentslide.halign": "left",
 "innerplaypause.hideOnMouseOut": false,
 "innernumbersitem.orientation": "horizontal",
 "innersubcaption.slideEffect": "fadeIn",
 "innerbullets_back.left": "-230px",
 "innerplaypause.play.hover.backgroundType": "normal",
 "innernavbaritemthumb.hover.mouseOverEffect": false,
 "innerbullets.hideOnMouseOut": false,
 "innernavbaritem.active.backgroundType": "",
 "innernumbers_next.valign": "top",
 "innersubcaption.slideEffectEasing": "linear",
 "innerbullets.width": "auto",
 "innernumbers.mouseOutEffect": "fadeIn",
 "innerbutton.next.halign": "right",
 "innerbutton.back.mouseOutEffectEasing": "linear",
 "innerbullets_next.halign": "center",
 "innercaption.opacity": "1",
 "imagearea.top": "0px",
 "loop": true,
 "tooltip.easing": "easeOut",
 "innerbullets_back.valign": "middle",
 "innerthumbscroll.left": "0px",
 "innerbutton.next.mouseOutEffectDuration": "300",
 "innernumbers.scrollerOrientation": "horizontal",
 "innerbutton.back.valign": "middle",
 "innerbullets.orientation": "horizontal",
 "innernumbers_next.halign": "left",
 "innerthumbscroll.scrollerOrientation": "horizontal",
 "innerbutton.next.top": "0px",
 "innernavbar.mouseOutEffectEasing": "linear",
 "innernavbar.scrollerOrientation": "horizontal",
 "innercurrentslide.top": "0px",
 "innerplaypause.play.backgroundType": "normal",
 "ease": "easeOut",
 "innernumbers.spacing": "0px",
 "innernumbers.opacity": "1",
 "innernavbaritem.spacing": "10px",
 "innerplaypause.valign": "top",
 "innernavbaritem.contentType": "image & text to right",
 "innernumbersitem.spacing": "0px",
 "innercurrentslide.opacity": "1",
 "resumeDuration": "3000",
 "innercurrentslide.hideOnMouseOut": false,
 "tooltip.show": false,
 "innerthumbscrollitemthumb.hover.mouseOverEffectEasing": "linear",
 "innerbutton.back.mouseOutEffectDuration": "300",
 "innernumbers_back.halign": "left",
 "innernavbar.left": "0px",
 "tooltip.side": "right",
 "innernavbaritemthumb.hover.opacity": "1",
 "innerthumbscrollitemthumb.opacity": "1",
 "innernavbar_back.opacity": "1",
 "innerbullets_back.opacity": "1",
 "innernavbar.hideOnMouseOut": false,
 "thumbscroll.scrollerOrientation": "horizontal",
 "relPath": "",
 "navbar_next.opacity": "1",
 "innerplaypause.pause.hover.backgroundType": "normal",
 "innerbutton.next.opacity": 1,
 "pauseTime": "5000",
 "innerbullets.halign": "right",
 "innerthumbscrollitemthumb.hover.mouseOverEffect": false,
 "innersubcaption.hideOnMouseOut": false,
 "innerbullets_back.top": "0px",
 "innercurrentslide.valign": "top",
 "innernavbar.orientation": "horizontal",
 "innernavbar.scrollerType": "noScroll",
 "innercaption.mouseOutEffect": "fadeIn",
 "innerthumbscrollitemthumb.hover.mouseOverEffectDuration": "2000",
 "innerthumbscroll.halign": "left",
 "innernumbers_back.left": "0px",
 "thumbscroll_next.opacity": "1",
 "innernumbers_next.left": "0px",
 "innerplaypause.mouseOutEffect": "fadeIn",
 "innerbullets.top": "10px",
 "innercaption.hideOnMouseOut": false,
 "innernumbers.mouseOutEffectDuration": "1000",
 "continuous": true,
 "tooltip.offsX": "0px",
 "innerbullets_next.top": "0px",
 "innercurrentslide.slideEffect": "fadeIn",
 "innerbutton.next.mouseOutEffect": "slideFromRight",
 "thumbscrollitem.orientation": "horizontal",
 "innerplaypause.mouseOutEffectEasing": "linear",
 "innerbutton.next.valign": "bottom",
 "innernumbers.valign": "bottom",
 "innercurrentslide.mouseOutEffectEasing": "linear",
 "innercurrentslide.mouseOutEffectDuration": "1000",
 "innerbulletsitem.orientation": "horizontal",
 "innerthumbscroll.top": "0px",
 "innerplaypause.opacity": 1,
 "innerthumbscroll.opacity": "1",
 "innernavbaritem.hover.backgroundType": "",
 "innerplaypause.pause.backgroundType": "normal",
 "innerthumbscrollitemthumb.active.opacity": "1",
 "innerbullets.opacity": "1",
 "innerplaypause.left": "15px",
 "innernumbers.hideOnMouseOut": false,
 "currentslide.opacity": "1",
 "innernavbar.top": "0px",
 "innersubcaption.mouseOutEffectDuration": "1000",
 "innercaption.mouseOutEffectDuration": "1000",
 "tooltip.width": "60px",
 "innerbutton.back.left": "0px",
 "innernumbers.orientation": "horizontal",
 "caption.opacity": "1",
 "innersubcaption.mouseOutEffectDelay": "0",
 "tooltip.height": "50px",
 "thumbscroll_back.opacity": "1",
 "innernavbar.halign": "left",
 "innerbullets.mouseOutEffectDuration": "1000",
 "innerbulletsitem.spacing": "10px",
 "innerbullets_next.valign": "middle",
 "innerbutton.hover.backgroundType": "normal",
 "innerbullets.mouseOutEffect": "fadeIn",
 "innerbullets.mouseOutEffectEasing": "linear",
 "innernumbers.halign": "right",
 "innerbullets.height": "auto",
 "innernumbers.scrollerType": "noScroll",
 "tooltip.speed": "500",
 "innerbutton.next.mouseOutEffectEasing": "linear",
 "pause": "1000",
 "innercaption.mouseOutEffectEasing": "linear",
 "innernavbar_next.opacity": "1",
 "innercurrentslide.mouseOutEffect": "fadeIn",
 "innerbutton.back.halign": "left",
 "innercurrentslide.left": "0px",
 "innerbutton.back.mouseOutEffect": "slideFromLeft",
 "innerbutton.back.opacity": 1,
 "innernavbar.mouseOutEffectDuration": "500",
 "innersubcaption.mouseOutEffectEasing": "linear",
 "innernumbers_back.opacity": "1",
 "innercaption.slideEffectEasing": "linear",
 "innernavbaritemthumb.opacity": "1",
 "navbar_back.opacity": "1",
 "innernumbers.left": "0px",
 "innerthumbscroll.scrollerType": "noScroll",
 "innernumbers.mouseOutEffectEasing": "linear",
 "innerbulletsitem.hover.backgroundType": "normal",
 "backgroundType": "normal",
 "innernavbar.opacity": "1",
 "innerbullets_next.opacity": "1",
 "innerbullets.left": "33px",
 "innerbutton.back.hideOnMouseOut": true,
 "innerthumbscroll_next.opacity": "1",
 "innerbullets.valign": "bottom",
 "innerbutton.back.backgroundType": "normal",
 "innernavbar.mouseOutEffect": "slideFromBottom",
 "vertical": false,
 "innerthumbscroll.valign": "top",
 "innernavbaritemthumb.hover.mouseOverEffectDuration": "2000",
 "sliderEffect": "slide",
 "innerbutton.next.backgroundType": "normal",
 "imagearea.left": "0px"
};


var jQuerySlideshow1_source = [{"link":"http://photocreations.michaels.com/create-photo-books","description":"10% off entire order","title":"Digital Scrapbooking","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/Splash_Banner_8_5.jpg","target":"_self"},{"link":"http://personalizedinvitations.michaels.com/Wedding-Invitations/View-All-Wedding-Invitations/index.cat","description":"20% off on entire order","title":"Custom Invites","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/ci_splash_banner_8_5_wf.jpg","target":"_self"},{"link":"http://personalizedinvitations.michaels.com/Stationery/View-All-Stationery/index.cat","description":"25% off on Personalized stationery and thank you notes.","title":"Personalized Stationery","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/ps_splash_banner_8_5.jpg","target":"_self"},{"link":"http://photocreations.michaels.com/create-calendars","description":"Custom Calanders","title":"Custom Photo Calendars","src":"includes/jQuerySlideshow/images/jQuerySlideshow1/Sunday15_PhotoCreationsCalendar_944x350.jpg","target":"_self"}];
var jQuerySlideshow1_slideshow = null;	

xtd_jQuerySlideshow(document).ready(function(){
	var $ = xtd_jQuerySlideshow;
	var jQuery = xtd_jQuerySlideshow;
	
	$("#jQuerySlideshow1Container").hide();
	
	// fix bug on webkit//
	if (jQuery.browser.webkit && document.readyState != "complete") {
		setTimeout( createJQuerySlideShow, 100 );
	} else {
		createJQuerySlideShow()
	}
		
	function createJQuerySlideShow() {

		if (document.readyState && document.readyState != "complete") {
			setTimeout( createJQuerySlideShow, 100 );
			return;
		}

		//show element first as height/width of auto elements is 0 if container is hidden//
		$("#jQuerySlideshow1Container").show();
		
		// create the slider
		jQuerySlideshow1_slideshow = $("#jQuerySlideshow1").jQuerySlideShow();
	}
});